
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class ProgramTest {
    @Test
    public void testSubnet() {
        String expected = "192.168.3.";

        String actual = Program.getSubnet("192.168.3.273");
        assertEquals("192.168.3.273", expected, actual);

        actual = Program.getSubnet("192.168.3.32");
        assertEquals("192.168.3.32", expected, actual);
    }
    
}
